name: Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run Linters
        run: pnpm run lint
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Unit Test & Coverage
        run: pnpm i -D lcov && pnpm run coverage
      - name: Unit Test
        run: pnpm run test:unit
      - name: Install LCov
        run: pnpm i -D lcov
      - name: Code Quality & Coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --user root
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: E2E Test
        run: pnpm run test:e2e